### ISSUE TITLE
Power Labels are reversed and....

### ISSUE THREAD

**Issue by Dwvsplat** [bitfocus/companion-module-sharp-tv#2]
This would be for the PN-L901
The quick power and standby power labels are reversed (off is on).
Also, the quick power on/off turns the network card on or off (so maybe label this network card on or off), which only needs to be turned on once.

See below:

[IP Power Sharp TV.pdf](https://github.com/bitfocus/companion-module-sharp-tv/files/5990694/IP.Power.Sharp.TV.pdf)

**Comment by McHauge** [comment]
@Dwvsplat Hi the core just got updated so the power buttons should now be in the right order, and renamed the quick power to "network card". Therefore I'll close this for now, as it can now be used in the beta builds
